### ISSUE TITLE
Intermittent error on selenium tests

### ISSUE THREAD

**Issue by kitchoi** [simphony/simphony-remote#162]
Intermittent error, rebuilding travis can pass the same test
https://travis-ci.org/simphony/simphony-remote/builds/147201071
```
======================================================================
ERROR: test_login_logout (selenium_tests.test_login_logout.TestLoginLogout)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/simphony/simphony-remote/selenium_tests/test_login_logout.py", line 20, in setUp
    capabilities=capabilities)
  File "/home/travis/virtualenv/python3.4.3/lib/python3.4/site-packages/selenium/webdriver/firefox/webdriver.py", line 80, in __init__
    self.binary, timeout)
  File "/home/travis/virtualenv/python3.4.3/lib/python3.4/site-packages/selenium/webdriver/firefox/extension_connection.py", line 52, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/home/travis/virtualenv/python3.4.3/lib/python3.4/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/home/travis/virtualenv/python3.4.3/lib/python3.4/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 108, in _wait_until_connectable
    % (self.profile.path))
selenium.common.exceptions.WebDriverException: Message: Can't load the profile. Profile Dir: /tmp/tmpgoc8hjk_ If you specified a log_file in the FirefoxBinary constructor, check it for details.
----------------------------------------------------------------------
Ran 2 tests in 55.902s
```

**Comment by stefanoborini** [comment]
The error message is deceiving. from the code it's actually a timeout error.
