### ISSUE TITLE
Occasional http proxy problem when remoteappmanager is not used for a while

### ISSUE THREAD

**Issue by stefanoborini** [simphony/simphony-remote#247]
The configurable-http-proxy apparently is unable to forward any request to jupyterhub in some obscure circumstances. This is the result of the log

```
    at createHangUpError (_http_client.js:250:15)
    at Socket.socketCloseListener (_http_client.js:282:23)
    at emitOne (events.js:95:20)
    at Socket.emit (events.js:182:7)
    at TCP._onclose (net.js:475:12)
22:34:31.915 - error: [ConfigProxy] 503 GET /hub/logout
22:34:52.077 - error: [ConfigProxy] Failed to get custom error page Error: connect ETIMEDOUT 172.17.5.167:8081
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1059:14)
22:34:52.078 - error: [ConfigProxy] Uncaught Exception TypeError: this._handle_proxy_error_default is not a function
    at ClientRequest.<anonymous> (/Users/sborini/Work/github/simphony/simphony-remote/node_modules/configurable-http-proxy/lib/configproxy.js:333:18)
    at emitOne (events.js:90:13)
    at ClientRequest.emit (events.js:182:7)
    at Socket.socketErrorListener (_http_client.js:306:9)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at emitErrorNT (net.js:1249:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
22:34:52.078 - error: [ConfigProxy] Failed to get custom error page Error: socket hang up
    at createHangUpError (_http_client.js:250:15)
    at Socket.socketCloseListener (_http_client.js:282:23)
    at emitOne (events.js:95:20)
    at Socket.emit (events.js:182:7)
    at TCP._onclose (net.js:475:12)
22:34:52.078 - error: [ConfigProxy] Uncaught Exception TypeError: this._handle_proxy_error_default is not a function
    at ClientRequest.<anonymous> (/Users/sborini/Work/github/simphony/simphony-remote/node_modules/configurable-http-proxy/lib/configproxy.js:333:18)
    at emitOne (events.js:90:13)
    at ClientRequest.emit (events.js:182:7)
    at Socket.socketCloseListener (_http_client.js:282:9)
    at emitOne (events.js:95:20)
    at Socket.emit (events.js:182:7)
    at TCP._onclose (net.js:475:12)
```

It seems like the forwarding finds a closed port at 8081, instead of jupyterhub. netstat in fact confirms that port 8081 is closed. This is unlikely to be due to our software, but it's worth investigating on our side and eventually fix it for jupyterhub, especially because it basically denies access to everything.

**Comment by stefanoborini** [comment]
Interestingly enough, port 8001 (the hub api) is available

```
(venv) sborini@MacBook-Pro:simphony-remote (v0.7.0) [9 stash] $ telnet 127.0.0.1 8001
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
GET / HTTP/1.0

HTTP/1.1 404 Not Found
Date: Mon, 19 Sep 2016 21:44:03 GMT
Connection: close

Not FoundConnection closed by foreign host.
(venv) sborini@MacBook-Pro:simphony-remote (v0.7.0) [9 stash] $ telnet 127.0.0.1 8081
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
telnet: Unable to connect to remote host
```

**Comment by stefanoborini** [comment]
I refined down the problem to a network switch between home and office. The above connection was done while at home. I am back in the office and the IP have been reassigned, so the connection works again. I didn't spot that at first.
