### ISSUE TITLE
ElementClickInterceptedException: Element is not clickable because another element obscures it

### ISSUE THREAD

**Issue by peterzahemszky** [simphony/simphony-remote#587]
"test_create_new_entry_button" [fails on CI](https://github.com/simphony/simphony-remote/runs/4549774806) with an error message similar to
```
ElementClickInterceptedException: Element is not clickable because another element obscures it
```

```
ERROR: test_create_new_entry_button (selenium_tests.test_user_accounting.TestUserAccounting)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/simphony-remote/simphony-remote/selenium_tests/AdminDriverTest.py", line 83, in tearDown
    self.logout()
  File "/home/runner/work/simphony-remote/simphony-remote/selenium_tests/RemoteAppDriverTest.py", line 272, in logout
    self.click_first_element_located(By.ID, "user-menu")
  File "/home/runner/work/simphony-remote/simphony-remote/selenium_tests/RemoteAppDriverTest.py", line 177, in click_first_element_located
    element.click()
  File "/home/runner/work/simphony-remote/simphony-remote/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/runner/work/simphony-remote/simphony-remote/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/runner/work/simphony-remote/simphony-remote/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/runner/work/simphony-remote/simphony-remote/venv/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: Element <li id="user-menu" class="dropdown user user-menu"> is not clickable at point (1100,25) because another element <div class="modal modal-display modal-fade-leave-active modal-fade-leave-to"> obscures it
```

**Comment by peterzahemszky** [comment]
Resolved by simply re-running CI: https://github.com/simphony/simphony-remote/runs/4549988282?check_suite_focus=true#step:9:1936

**Comment by peterzahemszky** [comment]
Appeared again on a seemingly unrelated branch: https://github.com/simphony/simphony-remote/runs/4559581966?check_suite_focus=true

**Comment by flongford** [comment]
I think this happens when one of the test docker image containers is not cleaned up properly, which causes a popup to appear with a 500 error during subsequent tests, and thereby obscuring the logout button in the user menu.

I've no idea why the container is not properly cleaned up though.
