### ISSUE TITLE
Test error for sqlite and threads

### ISSUE THREAD

**Issue by stefanoborini** [simphony/simphony-remote#99]
I noticed this error in the tests. Not sure if it's expected. The test itself doesn't fail, but maybe it's worth a check.

```
test_start_container_exception_cleanup_2 (tests.docker.test_container_manager.TestContainerManager) ... [I 160714 12:39:04 container_manager:169] Got container image: imageid
[I 160714 12:39:04 container_manager:211] Mounting these volumes: 
    
[I 160714 12:39:04 container_manager:244] Created container 'remoteexec-username-mapping_5Fid' (id: containerid) from image imageid
[E 160714 12:39:04 pool:643] Exception during reset or similar
    Traceback (most recent call last):
      File "/home/travis/virtualenv/python3.4.3/lib/python3.4/site-packages/sqlalchemy/pool.py", line 636, in _finalize_fairy
        fairy._reset(pool)
      File "/home/travis/virtualenv/python3.4.3/lib/python3.4/site-packages/sqlalchemy/pool.py", line 776, in _reset
        pool._dialect.do_rollback(self)
      File "/home/travis/virtualenv/python3.4.3/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 420, in do_rollback
        dbapi_connection.rollback()
    sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 140117046863680 and this is thread id 140116906829568
[E 160714 12:39:04 pool:293] Exception closing connection <sqlite3.Connection object at 0x7f6f827c3810>
    Traceback (most recent call last):
      File "/home/travis/virtualenv/python3.4.3/lib/python3.4/site-packages/sqlalchemy/pool.py", line 636, in _finalize_fairy
        fairy._reset(pool)
      File "/home/travis/virtualenv/python3.4.3/lib/python3.4/site-packages/sqlalchemy/pool.py", line 776, in _reset
        pool._dialect.do_rollback(self)
      File "/home/travis/virtualenv/python3.4.3/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 420, in do_rollback
        dbapi_connection.rollback()
    sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 140117046863680 and this is thread id 140116906829568
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/travis/virtualenv/python3.4.3/lib/python3.4/site-packages/sqlalchemy/pool.py", line 290, in _close_connection
        self._dialect.do_close(connection)
      File "/home/travis/virtualenv/python3.4.3/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 426, in do_close
        dbapi_connection.close()
    sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 140117046863680 and this is thread id 140116906829568
```

**Comment by kitchoi** [comment]
Can you refer to a link in travis please?  I can't find these errors for the most recent build of the master branch.  Is this for the master branch?

**Comment by stefanoborini** [comment]
https://travis-ci.org/simphony/simphony-remote/builds/144727068

**Comment by kitchoi** [comment]
I have encountered similar errors when implementing #95.  One needs to so `session.expunge(instance)` to detach an instance from a session for it to be used by another session (e.g. on a different thread).  When using the the expunged instance in a different session, the instance needs to be added back by doing `session.add(instance)`.

**Comment by stefanoborini** [comment]
Ok, but why is there another thread using it? 

It makes sense, in theory, but I don't understand the underlying problem.

**Comment by itziakos** [comment]
@kitchoi  since the PR about the `session` creation has been merged this issue is fixed now correct?

**Comment by kitchoi** [comment]
@itziakos I also believe this bug refers to a branch that is not master.  I could not find the same bug on the most recent master build https://travis-ci.org/simphony/simphony-remote/builds/145002821

**Comment by itziakos** [comment]
ok
